#!/bin/bash
set -euo pipefail

export all_proxy=${all_proxy:-http://127.0.0.1:7890}

# Minimal active-sensing simulation training suite.
# Default modes: ours, fixed camera, random static camera, detached sensor gradient.
# Optional zero-depth counterfactual can be evaluated from the ours checkpoint.

BASE_CONFIG=${BASE_CONFIG:-configs/paper_final_full.args}
MODES=${MODES:-"ours"}
PREFIX=${PREFIX:-$(basename "${BASE_CONFIG%.args}")_auto}

if [ ! -f "$BASE_CONFIG" ]; then
	echo "[error] base config not found: $BASE_CONFIG"
	exit 1
fi

make_override_block() {
	local mode="$1"
	case "$mode" in
		ours)
			cat <<'EOF'
--policy_depth_mode depth
--camera_control_mode learned
--sensor_grad_mode full
EOF
			;;
		nondiff)
			cat <<'EOF'
--policy_depth_mode depth
--camera_control_mode learned
--sensor_grad_mode detached
EOF
			;;
		fix|fixed)
			cat <<'EOF'
--policy_depth_mode depth
--camera_control_mode fixed
--sensor_grad_mode full
--coef_cam_smooth 0.0
--coef_diff_depth_power 0.0
--coef_diff_depth_blur 0.0
--coef_diff_depth_noise 0.0
--coef_diff_depth_fill 0.0
--diff_depth_min_fill_rate 0.0
EOF
			;;
		randfix|fixed_random|fixed_random_static)
			cat <<'EOF'
--policy_depth_mode depth
--camera_control_mode fixed_random_static
--sensor_grad_mode full
--coef_cam_smooth 0.0
--coef_diff_depth_power 0.0
--coef_diff_depth_blur 0.0
--coef_diff_depth_noise 0.0
--coef_diff_depth_fill 0.0
--diff_depth_min_fill_rate 0.0
EOF
			;;
		zero|nocamera)
			cat <<'EOF'
--policy_depth_mode zero
--camera_control_mode fixed
--sensor_grad_mode detached
EOF
			;;
		*)
			echo "[error] unsupported mode: $mode" >&2
			return 1
			;;
	esac
}

write_base_without_mode_overrides() {
	local mode="${1:-}"
	local drop_camera_losses=0
	case "$mode" in
		fix|fixed|randfix|fixed_random|fixed_random_static|zero|nocamera)
			drop_camera_losses=1
			;;
	esac
	awk -v drop_camera_losses_env="$drop_camera_losses" '
		BEGIN { drop_camera_losses = int(drop_camera_losses_env) }
		/^[[:space:]]*# Generated by run_train_modes\.sh[[:space:]]*$/ { next }
		/^[[:space:]]*# mode:[[:space:]]*/ { next }
		/^[[:space:]]*--(policy_depth_mode|camera_control_mode|sensor_grad_mode)([[:space:]]|$)/ { next }
		drop_camera_losses && /^[[:space:]]*--(coef_cam_smooth|coef_diff_depth_power|coef_diff_depth_blur|coef_diff_depth_noise|coef_diff_depth_fill|diff_depth_min_fill_rate)([[:space:]]|$)/ { next }
		{ print }
	' "$BASE_CONFIG"
}

generated_tasks=()
for mode in $MODES; do
	task_name="${PREFIX}_${mode}"
	task_file="configs/${task_name}.args"
	write_base_without_mode_overrides "$mode" > "$task_file"
	{
		echo
		echo "# Generated by run_train_modes.sh"
		echo "# mode: ${mode}"
		make_override_block "$mode"
	} >> "$task_file"
	generated_tasks+=("$task_name")
	echo "[train-suite] mode=${mode} task=${task_name}"
	TASK="$task_name" bash run.sh
done

echo "[train-suite] completed modes:"
printf '  - %s\n' "${generated_tasks[@]}"
